apiVersion: apps/v1
kind: Deployment
metadata:
  name: remix-weather-app
  namespace: weather          # <-- add this (or keep default if you prefer)
spec:
  replicas: 1
  selector:
    matchLabels:
      app: remix-weather-app
  template:
    metadata:
      labels:
        app: remix-weather-app
    spec:
      containers:
        - name: remix-weather
          image: IMAGE_PLACEHOLDER   # <-- was acr.../remix-weather:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: WEATHER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: weather-secret
                  key: WEATHER_API_KEY
