apiVersion: apps/v1
kind: Deployment
metadata:
  name: remix-weather-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: remix-weather-app
  template:
    metadata:
      labels:
        app: remix-weather-app
    spec:
      containers:
        - name: remix-weather
          image: <your-acr-name>.azurecr.io/remix-weather:latest
          ports:
            - containerPort: 3000
          env:
            - name: WEATHER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: weather-secret
                  key: WEATHER_API_KEY
