apiVersion: v1
kind: Service
metadata:
  name: remix-weather-service
spec:
  type: LoadBalancer
  selector:
    app: remix-weather-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
