name: Terraform Apply

on:
  push:
    branches: [ main ]
    paths:
      - "infra/**"
      - ".github/workflows/terraform-apply.yml"

permissions:
  id-token: write
  contents: read

concurrency:
  group: terraform-apply-prod
  cancel-in-progress: true

env:
  TF_IN_AUTOMATION: true

jobs:
  apply:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure OIDC Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform init (prod)
        run: terraform -chdir=infra/envs/prod init -input=false -no-color

      - name: Terraform apply (prod)
        env:
          TF_VAR_weather_api_key: ${{ secrets.WEATHER_API_KEY }}
        run: |
          terraform -chdir=infra/envs/prod apply \
            -auto-approve \
            -input=false \
            -lock=true \
            -lock-timeout=5m \
            -no-color
