name: Terraform Static Checks

on:
  push:
    paths:
      - "infra/**"
      - ".github/workflows/terraform-static.yml"

permissions:
  id-token: write
  contents: read

concurrency:
  group: terraform-static-${{ github.ref }}
  cancel-in-progress: true

env:
  TF_IN_AUTOMATION: true

jobs:
  static:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure OIDC Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform fmt (recursive)
        run: terraform fmt -check -recursive

      - name: Cache .terraform
        uses: actions/cache@v4
        with:
          path: infra/.terraform
          key: tf-${{ runner.os }}-${{ hashFiles('infra/**/*.tf') }}
          restore-keys: |
            tf-${{ runner.os }}-

      - name: Terraform init (remote backend)
        working-directory: infra
        run: terraform init -input=false -no-color

      - name: Terraform validate
        working-directory: infra
        run: terraform validate -no-color

      - name: tfsec (security scan)
        uses: aquasecurity/tfsec-action@v1
        with:
          working_directory: infra

      - name: Setup tflint
        uses: terraform-linters/setup-tflint@v4

      - name: tflint
        working-directory: infra
        run: |
          tflint --version
          tflint -f compact
