name: Terraform Lint & Plan

on:
  pull_request:
    branches: [ main ]
    paths:
      - "infra/**"
      - ".github/workflows/terraform-plan.yml"

permissions:
  id-token: write
  contents: read
  pull-requests: write

concurrency:
  group: terraform-plan-${{ github.ref }}
  cancel-in-progress: true

env:
  TF_IN_AUTOMATION: true

jobs:
  plan:
    runs-on: ubuntu-latest

    outputs:
      has_changes: ${{ steps.set_change_flag.outputs.has_changes }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure OIDC Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Setup tflint
        uses: terraform-linters/setup-tflint@v4

      - name: tflint
        run: |
          tflint --version
          tflint -f compact
        working-directory: infra

      - name: Cache .terraform (test)
        uses: actions/cache@v4
        with:
          path: infra/envs/test/.terraform
          key: tf-${{ runner.os }}-${{ hashFiles('infra/**/*.tf') }}
          restore-keys: |
            tf-${{ runner.os }}-

      - name: Terraform init (test)
        run: terraform -chdir=infra/envs/test init -input=false -no-color

      - name: Terraform plan (test)
        id: plan
        run: |
          set +e
          terraform -chdir=infra/envs/test plan \
            -no-color \
            -input=false \
            -lock=true \
            -lock-timeout=5m \
            -detailed-exitcode \
            -out=tfplan
          exitcode=$?
          # Map Terraform's special exit codes: 0=no changes, 2=changes, 1=error
          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
          # Always produce a human-readable plan file for reviewers
          terraform -chdir=infra/envs/test show -no-color tfplan > infra/envs/test/tfplan.txt
          exit $([ $exitcode -eq 1 ] && echo 1 || echo 0)

      - name: Upload plan artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-${{ github.sha }}
          path: |
            infra/envs/test/tfplan
            infra/envs/test/tfplan.txt

      - name: Set change flag
        id: set_change_flag
        run: |
          if [ "${{ steps.plan.outputs.exitcode }}" = "2" ]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: PR summary & comment
        uses: actions/github-script@v7
        env:
          HAS_CHANGES: ${{ steps.set_change_flag.outputs.has_changes }}
        with:
          script: |
            const hasChanges = process.env.HAS_CHANGES === 'true';
            const body = hasChanges
              ? `✅ **Plan succeeded** and **changes are detected**.\n\nArtifact: \`tfplan-${process.env.GITHUB_SHA}\` (includes \`tfplan\` & \`tfplan.txt\`).`
              : `✅ **Plan succeeded** and **no changes** were detected.\n\nNothing to apply.`;
            core.summary.addHeading('Terraform Plan');
            core.summary.addRaw(body);
            await core.summary.write();
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body
            });
